source 'https://rubygems.org'
ruby '1.9.2'

gem 'rake'
gem 'sinatra'
gem 'rack-jsonp', :require => 'rack/jsonp'
gem 'dm-core'
gem 'dm-aggregates'
gem 'dm-migrations'
gem 'dm-serializer'
gem 'dm-timestamps'
gem 'dm-types'
gem 'dm-postgres-adapter'
gem 'unicorn'