source 'https://rubygems.org'
ruby '1.9.2'

gem 'rake'
gem 'sinatra'
gem 'rack-jsonp', :require => 'rack/jsonp'
gem 'dm-core'
gem 'dm-aggregates'
gem 'dm-migrations'
gem 'dm-serializer'
gem 'dm-timestamps'
gem 'dm-types'
gem 'dm-postgres-adapter'
gem 'unicorn'
gem 'sentry-raven'
gem 'newrelic_rpm'
gem 'i18n'
gem 'active_support', :require => ['active_support/lazy_load_hooks', 'active_support/core_ext/string']