source 'https://rubygems.org'
ruby '2.1.2'

gem 'rake'
gem 'sinatra'
gem 'rack-cors'
gem 'haml'
gem 'stripe'
gem 'dotenv'
gem 'dm-core'
gem 'dm-aggregates'
gem 'dm-migrations'
gem 'dm-serializer'
gem 'dm-timestamps'
gem 'dm-types'
gem 'dm-postgres-adapter'
gem 'puma'
gem 'sentry-raven'
gem 'newrelic_rpm'
gem 'i18n'
gem 'activesupport', :require => ['active_support/lazy_load_hooks', 'active_support/core_ext/string']
